language: java

addons:
  sonarcloud:
    organization: "jcornaz-github"

branches:
  only:
    - master
    - develop

git:
  depth: false

jdk:
  - oraclejdk11

script:
  - ./travis_script.sh

cache:
  directories:
    - $HOME/.gradle/
