language: java

addons:
  sonarcloud:
    organization: "jcornaz-github"

branches:
  only:
    - master
    - develop
    - /^release.*$/

jdk:
  - oraclejdk11

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check sonarqube --no-daemon

cache:
  directories:
    - $HOME/.gradle/
