build:
  maxIssues: 10

complexity:
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 10
    thresholdInInterfaces: 5
    thresholdInObjects: 10
    thresholdInEnums: 5
    ignoreDeprecated: true
  LongParameterList:
    ignoreDefaultParameters: true

exceptions:
  TooGenericExceptionCaught:
    active: false