site:
  title: Kwik
  url: https://jcornaz.github.io/kwik
  start_page: 0.1@kwik::getting-started.adoc

content:
  sources:
    - url: git@github.com:jcornaz/kwik.git
      branches: master
      start_path: docs

ui:
  bundle:
    url: https://filedn.com/lMOjCKJNGah8zSJzM4ELaAh/kwik-ui-bundle.zip
    snapshot: true
